apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: backend
          image: 192.168.1.160:49939/todo-backend:latest
          readinessProbe:
            httpGet:
              path: /api/v1/auth/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: 'production'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET_KEY
